# Generated by Django 3.1.2 on 2020-12-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_skills',
            name='skill_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offers_made',
            name='matching_skills',
            field=models.IntegerField(),
        ),
    ]
