# Generated by Django 3.1.2 on 2020-12-06 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_listing_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listing_skills',
            unique_together={('listing_id', 'skill_id')},
        ),
    ]
