# Generated by Django 3.1.2 on 2020-12-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20201207_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='compensation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
