# Generated by Django 3.1.3 on 2020-12-09 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20201208_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing_skills',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='listing_skills',
            old_name='skill_id',
            new_name='skill',
        ),
    ]
