# Generated by Django 3.1.2 on 2020-12-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20201205_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='offers_made',
            name='id',
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='offers_made',
            name='offer_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
