# Generated by Django 3.1.2 on 2020-12-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20201205_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='offers_made',
            old_name='applicant_id',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='offers_made',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
