# Generated by Django 3.1.2 on 2020-12-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20201205_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_skills',
            name='skill_listing_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing_skills',
            name='listing_id',
            field=models.IntegerField(default=0),
        ),
    ]
