# Generated by Django 3.1.2 on 2020-12-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
