# Generated by Django 3.1.2 on 2020-12-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='id',
            new_name='applicant_id',
        ),
    ]
