# Generated by Django 3.1.2 on 2020-12-10 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers_review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('compensation', models.DecimalField(decimal_places=2, max_digits=8)),
                ('satisfaction', models.IntegerField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.applicant')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=300)),
                ('timesent', models.DateTimeField(auto_now=True)),
                ('sender_applicant', models.BooleanField(default=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.applicant')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='applicant_skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_value', models.IntegerField(default=1)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.applicant')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.skill')),
            ],
        ),
        migrations.CreateModel(
            name='applicant_listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.applicant')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.listing')),
            ],
        ),
    ]
