# Generated by Django 3.1.2 on 2020-12-06 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant_skills',
            old_name='applicant_id',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='applicant_skills',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='applicant_id',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='mentor_id',
            new_name='mentor',
        ),
        migrations.RenameField(
            model_name='offers_review',
            old_name='applicant_id',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='offers_review',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
