# Generated by Django 3.1.2 on 2020-12-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offers_review',
            name='review_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
