# Generated by Django 3.1.3 on 2020-12-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_skills',
            name='skill_value',
            field=models.IntegerField(default=1),
        ),
    ]
