# Generated by Django 3.1.3 on 2020-12-09 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('organization', '0004_auto_20201208_1854'),
        ('applicant', '0002_applicant_skills_skill_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant_listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.applicant')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.listing')),
            ],
        ),
    ]
