# Generated by Django 3.1.2 on 2020-12-06 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_auto_20201206_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant_skills',
            old_name='applicant',
            new_name='applicant_id',
        ),
        migrations.RenameField(
            model_name='applicant_skills',
            old_name='skill',
            new_name='skill_id',
        ),
    ]
